language: php

php:
  - 5.6

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  # Navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # Install Drush
  - mkdir ~/.bin
  - wget https://github.com/drush-ops/drush/releases/download/8.1.10/drush.phar -O ~/.bin/drush
  - chmod +x ~/.bin/drush
  - export PATH=$PATH:~/.bin

  # Install php packages required for running Drupal
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes php5-mysql

  # Create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database drupal'
  - php -d sendmail_path=`which true`
  - drush --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/drupal --enable=simpletest og

  # Reference and enable module in build site
  - ln -s $(readlink -e $(cd -)) og/drupal/sites/all/modules/og
  - cd og/drupal

  # Enable OG-UI, so drush will auto-download all dependencies
  - drush --yes pm-enable og_ui

script:
  - php ./og/drupal/scripts/run-tests.sh --concurrency 4 --verbose --color "Organic groups","Organic groups access","Organic groups context","Organic groups field access","Organic groups UI" 2>&1 | tee /tmp/simpletest-result.txt
  - egrep -i "([1-9]+ fail)|(Fatal error)|([1-9]+ exception)" /tmp/simpletest-result.txt && exit 1
