og.group_resolver_negotiation.*:
  type: config_entity
  label: 'OG group resolver negotiation config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    status:
      type: boolean
      label: 'Status'
    weight:
      type: integer
      label: 'Weight'
