og.og_context_negotiation.*:
  type: config_entity
  label: 'OG context negotiation config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
